+incdir+..
codigo_hdl/fetch/fetch.sv
codigo_hdl/fetch/i_cache.v
codigo_hdl/decoder/decoder.sv
codigo_hdl/decoder/imm_generator.sv
codigo_hdl/decoder/register_bank.sv
codigo_hdl/decoder/control_unit.sv
codigo_hdl/execution/simple_mux.sv
codigo_hdl/execution/execution.sv
codigo_hdl/execution/basic_comparator32.sv
codigo_hdl/execution/basic_shifter32.sv
codigo_hdl/execution/fowarding_unit.sv
codigo_hdl/execution/multiplexer.sv
codigo_hdl/execution/multiplexer_result.sv
codigo_hdl/execution/mux_fowarding_unit.sv
codigo_hdl/execution/basic_alu32.sv
codigo_hdl/memory/memory.sv
codigo_hdl/memory/store_unit.sv
codigo_hdl/memory/branch_unit.sv
codigo_hdl/memory/d_cache.v
codigo_hdl/write_back/load_unit.sv
codigo_hdl/write_back/write_back.sv
codigo_hdl/inst_mem_ctrl.sv
codigo_hdl/interrupt_controller.sv
codigo_hdl/top_architecture.sv
codigo_hdl/top_cpu.sv
tb.sv